#!/usr/bin/env python

import os
from os.path import join
from waflib.extras.gtest import summary
from waflib.extras.symwaf2ic import get_toplevel_path

def depends(ctx):
    ctx('pyublas')
    ctx('pywrap')
    ctx('haldls')
    ctx('halco', 'pyhalco')
    ctx('code-format')

def options(opt):
    opt.load('pytest')
    opt.load('pylint')
    opt.load('pycodestyle')

def configure(cfg):
    cfg.load('compiler_cxx')
    cfg.load('python')
    cfg.check_python_version()
    cfg.check_python_headers()
    cfg.load('pytest')
    cfg.load('genpybind')
    cfg.load('pylint')
    cfg.load('pycodestyle')

    if cfg.env.with_pybind:
        cfg.check(
            compiler='cxx',
            features='cxx pyembed',
            uselib_store='PYBIND11HALDLS',
            mandatory=True,
            header_name='pybind11/pybind11.h',
        )

def build(bld):
    bld.env.DLSv2_HARDWARE_AVAILABLE = "dls" == os.environ.get("SLURM_JOB_PARTITION")
    bld.env.DLSvx_HARDWARE_AVAILABLE = "cube" == os.environ.get("SLURM_JOB_PARTITION")

    if not bld.env.with_pybind:
        bld.fatal('building pyhaldls requires pybind')

    bld(
        target='pyhaldls_v2',
        source='../include/haldls/v2/container.h',
        genpybind_tags='haldls_v2',
        features='genpybind cxx cxxshlib pyext',
        use=['haldls_v2', 'PYBIND11HALDLS'],
        install_path='${PREFIX}/lib',
        linkflags='-Wl,-z,defs',
    )

    bld(
        name='pyhaldls_test_v2',
        tests='test/pyhaldls_test_v2.py',
        features='use pytest pylint pycodestyle',
        use=['pyhalco_hicann_dls_v2', 'pyhaldls_v2', 'pyhalco_common_files'],
        install_path='${PREFIX}/bin',
        pylint_config=join(get_toplevel_path(), "code-format", "pylintrc"),
        pycodestyle_config=join(get_toplevel_path(), "code-format", "pycodestyle")
    )

    bld(
        target='pyhaldls_vx',
        source='../include/haldls/vx/haldls.h',
        genpybind_tags='haldls_vx',
        features='genpybind cxx cxxshlib pyext',
        use=['haldls_vx', 'PYBIND11HALDLS', 'pyfisch_vx'],
        install_path='${PREFIX}/lib',
        linkflags='-Wl,-z,defs',
    )

    bld(
        name='pyhaldls_hw_test_vx',
        tests='test/pyhaldls_test_v2.py',
        features='use pytest pylint pycodestyle',
        use=['pyhalco_hicann_dls_vx', 'pyhaldls_vx', 'pyhalco_common_files'],
        install_path='${PREFIX}/bin',
        pylint_config=join(get_toplevel_path(), "code-format", "pylintrc"),
        pycodestyle_config=join(get_toplevel_path(), "code-format", "pycodestyle"),
        skip_run=not bld.env.DLSvx_HARDWARE_AVAILABLE
    )

    bld.add_post_fun(summary)
