#!/usr/bin/env python

import os
from os.path import join
from waflib.extras.gtest import summary
from waflib.extras.symwaf2ic import get_toplevel_path

def depends(ctx):
    ctx('haldls')
    ctx('halco', 'pyhalco')
    ctx('code-format')

def options(opt):
    opt.load('pytest')
    opt.load('pylint')
    opt.load('pycodestyle')

def configure(cfg):
    cfg.load('compiler_cxx')
    cfg.load('python')
    cfg.check_python_version()
    cfg.check_python_headers()
    cfg.load('pytest')
    cfg.load('genpybind')
    cfg.load('pylint')
    cfg.load('pycodestyle')

def build(bld):
    bld.env.DLSvx_HARDWARE_AVAILABLE = "cube" == os.environ.get("SLURM_JOB_PARTITION")

    if not bld.env.with_pybind:
        bld.fatal('building pyhaldls requires pybind')

    bld(
        features='cxx pyembed',
        target='pyhaldls_vx_obj',
        source='../src/haldls/vx/pyhaldls.cpp',
        use='haldls_vx',
    )

    bld(
        target='pyhaldls_vx',
        source='../include/haldls/vx/pyhaldls.h',
        genpybind_tags='haldls_vx',
        features='genpybind cxx cxxshlib pyext pyembed',
        use=['haldls_vx', 'pyfisch_vx', 'pyhaldls_vx_obj'],
        install_path='${PREFIX}/lib',
        # Avoid warning; 1 OoM less and I see warnings (ECM)
        cxxflags='--param=max-vartrack-size=100000000',
        linkflags='-Wl,-z,defs',
    )

    bld(
        name='pyhaldls_test_vx',
        tests='test/pyhaldls_test_vx.py',
        features='use pytest pylint pycodestyle',
        use=['pyhalco_hicann_dls_vx', 'pyhaldls_vx', 'pyhalco_common_files'],
        install_path='${PREFIX}/bin',
        pylint_config=join(get_toplevel_path(), "code-format", "pylintrc"),
        pycodestyle_config=join(get_toplevel_path(), "code-format", "pycodestyle"),
        test_timeout=120
    )

    bld.add_post_fun(summary)
