#!/usr/bin/env python

from os.path import join
from waflib.extras.symwaf2ic import get_toplevel_path
from waflib.extras.gtest import summary
from waflib import Utils


def depends(ctx):
    ctx('code-format')
    ctx('pyhid')


def options(opt):
    opt.load('pytest')
    opt.load('pylint')
    opt.load('pycodestyle')


def configure(cfg):
    cfg.load('python')
    cfg.check_python_version()
    cfg.load('pytest')
    cfg.load('pylint')
    cfg.load('pycodestyle')


def build(bld):
    bld(name='tud_cube',
        features='use py',
        use='pyhid',
        source=['cube_ctrl.py', 'pyhid_cube.py'],
        relative_trick=True,
        install_path = '${PREFIX}/lib'
    )

    bld(name='cubetools',
        features='use py pylint pycodestyle',
        use='pyhid tud_cube',
        source=bld.path.ant_glob('hxcube_*.py'),
        pylint_config=join(get_toplevel_path(), "code-format", "pylintrc"),
        pycodestyle_config=join(get_toplevel_path(), "code-format", "pycodestyle"),
        relative_trick=True,
        chmod=Utils.O755,
        install_path = '${PREFIX}/bin'
    )

    bld.add_post_fun(summary)
