#!/usr/bin/env python

from os.path import join
from waflib.extras.symwaf2ic import get_toplevel_path
from waflib.extras.gtest import summary


def depends(ctx):
    ctx('code-format')
    ctx('pyhid')


def options(opt):
    opt.load('pytest')
    opt.load('pylint')
    opt.load('pycodestyle')


def configure(cfg):
    cfg.load('python')
    cfg.check_python_version()
    cfg.load('pytest')
    cfg.load('pylint')
    cfg.load('pycodestyle')


def build(bld):
    bld(name='tud_cube',
        features='py',
        source=['cube_ctrl.py', 'pyhid_cube.py'],
        relative_trick=True,
        install_path = '${PREFIX}/lib'
    )

    bld(name='cubetools',
        features='py pylint pycodestyle',
        source=bld.path.ant_glob('hxcube_*.py'),
        relative_trick=True,
        install_path = '${PREFIX}/bin',
        pylint_config=join(get_toplevel_path(), "code-format", "pylintrc"),
        pycodestyle_config=join(get_toplevel_path(), "code-format", "pycodestyle")
    )

    bld.add_post_fun(summary)
