#pragma once

#include "haldls/vx/arq.h"
#include "haldls/vx/cadc.h"
#include "haldls/vx/capmem.h"
#include "haldls/vx/jtag.h"
#include "haldls/vx/neuron.h"
#include "haldls/vx/padi.h"
#include "haldls/vx/perftest.h"
#include "haldls/vx/phy.h"
#include "haldls/vx/pll.h"
#include "haldls/vx/ppu.h"
#include "haldls/vx/reset.h"
#include "haldls/vx/spi.h"
#include "haldls/vx/synapse.h"
#include "haldls/vx/synapse_driver.h"
#include "haldls/vx/systime.h"
#include "haldls/vx/timer.h"
