@Library("jenlib") _

try {

	Map<String, Object> commonPipelineOptions = [
		projects           : ["haldls"],
		moduleOptions      : [modules: ["ppu-toolchain"]],
		testTimeout        : 240,
		notificationChannel: "#jenkins-trashbin"  // success is checked globally
	]

	Map<String, Object> pipelineDeploymentOptions = [
		container              : [app: "dls-nodev"],
		configureInstallOptions: "--build-profile=release_with_debug"
	] << commonPipelineOptions

	Map<String, Object> pipelineNoDeploymentOptions = [
		container              : [app: "dls-core"],
		configureInstallOptions: "--build-profile=release"
	] << commonPipelineOptions

	// Additional options for hardware testing in "no deployment" and not triggered by Gerrit case
	if (!isTriggeredByGerrit()) {
		pipelineNoDeploymentOptions << [
				testOptions       : "--test-execall -j1",
				testSlurmResource : [[partition: "cube", wafer: 62, "fpga-without-aout": 3]],
				preTestHook       : { configureHxCubeBitfile() },
		]
	}

	boolean deploy = env.GERRIT_EVENT_TYPE == "change-merged"

	Map<String, Object> pipelineOptions = deploy ? pipelineDeploymentOptions : pipelineNoDeploymentOptions

	withCcache() {
		wafDefaultPipeline(pipelineOptions)
	}

	conditionalStage(name: "Module Deployment", skip: !deploy) {
		runOnSlave(label: "frontend") {
			inSingularity(app: "dls-nodev") {
				deployModule([name: "haldls", source: "bin/ lib/ doc/ repos_log.txt"])
			}
		}
	}
} catch (Throwable t) {
	notifyFailure(mattermostChannel: "#dls-software")
	throw t
}

if (currentBuild.currentResult != "SUCCESS") {
	notifyFailure(mattermostChannel: "#dls-software")
}
