@Library("jenlib") _

wafDefaultPipeline(projects: ["haldls"],
                   container: [app: "visionary-dls"],
                   postPipelineCleanup: false,
                   testOptions: "--test-execall -j1",
                   testSlurmResource: [[partition: "dls", gres: "07"],
                                       [partition: "cube", wafer: 62, "fpga-without-aout": 3]],
                   testTimeout: 240,
                   notificationChannel: "#dls-software")
