@Library("jenlib") _

// HICANN-DLSv2
wafDefaultPipeline(projects: ["haldls"],
                   container: [app: "visionary-dls"],
                   postPipelineCleanup: false,
                   testOptions: "--test-execall -j1",
                   testSlurmResource: [partition: "dls", gres: "07"],
                   testTimeout: 240,
                   notificationChannel: "#dls-software")


// HICANN-X
wafDefaultPipeline(projects: ["haldls"],
                   container: [app: "visionary-dls"],
                   prePipelineCleanup: false,
                   testOptions: "--test-execall -j1",
                   testSlurmResource: [partition: "cube", gres: "cube1", licenses: "W4F3"],
                   notificationChannel: "#dls-software")
